@startuml
autonumber

skinparam sequence {
	ArrowColor blue

	LifeLineBorderColor blue
	LifeLineBackgroundColor #A9DCDF

	ParticipantBorderColor blue
	ParticipantBackgroundColor #A9DCDF
	ParticipantFontColor black

	ActorBorderColor blue
	ActorBackgroundColor #A9DCDF
}

<style>
	.success * {
		BackgroundColor #90ee90
		FontColor Black
		RoundCorner 10
	}
</style>

title Processing Requests by the AI Agent

Jinnee.Orchestrator -> Jinnee.Agent: Sends request as a text message
activate Jinnee.Orchestrator
activate Jinnee.Agent
Jinnee.Agent -> Jinnee.RAG: Sends request as a text message
activate Jinnee.RAG
Jinnee.RAG -> Jinnee.RAG: Processes the request (details in the "Processing Requests by Jinnee.RAG Component" diagram)
Jinnee.RAG --> Jinnee.Agent: Response
deactivate Jinnee.RAG
Jinnee.Agent --> Jinnee.Orchestrator: Response
deactivate Jinnee.Agent
deactivate Jinnee.Orchestrator
@enduml
